"""comment

Revision ID: 7b6a1fd10273
Revises: 95be8c7f8350
Create Date: 2025-04-13 11:29:29.381700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6a1fd10273'
down_revision: Union[str, None] = '95be8c7f8350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore_completion',
    sa.Column('chore_id', sa.UUID(), nullable=False),
    sa.Column('completed_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('awaits', 'canceled', 'approved', name='status_confirm', native_enum=False), nullable=False),
    sa.Column('message', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peer_transactions',
    sa.Column('transaction_type', sa.Enum('transfer', 'purchase', name='peer_transaction', native_enum=False), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('coins', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_transactions_from_user_id'), 'peer_transactions', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_peer_transactions_product_id'), 'peer_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_peer_transactions_to_user_id'), 'peer_transactions', ['to_user_id'], unique=False)
    op.create_table('product_buyers',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chore_confirmation',
    sa.Column('chore_completion_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('awaits', 'canceled', 'approved', name='status_confirm', native_enum=False), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chore_completion_id'], ['chore_completion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reward_transactions',
    sa.Column('transaction_type', sa.Enum('reward_for_chore', name='system_transaction', native_enum=False), nullable=False),
    sa.Column('chore_completion_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('coins', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['chore_completion_id'], ['chore_completion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_transactions_chore_completion_id'), 'reward_transactions', ['chore_completion_id'], unique=False)
    op.create_index(op.f('ix_reward_transactions_to_user_id'), 'reward_transactions', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_transactions_to_user_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_chore_completion_id'), table_name='reward_transactions')
    op.drop_table('reward_transactions')
    op.drop_table('chore_confirmation')
    op.drop_table('product_buyers')
    op.drop_index(op.f('ix_peer_transactions_to_user_id'), table_name='peer_transactions')
    op.drop_index(op.f('ix_peer_transactions_product_id'), table_name='peer_transactions')
    op.drop_index(op.f('ix_peer_transactions_from_user_id'), table_name='peer_transactions')
    op.drop_table('peer_transactions')
    op.drop_table('chore_completion')
    # ### end Alembic commands ###
