"""Add default_chore_id to Chore model

Revision ID: 052e044604d3
Revises: d778d62ab147
Create Date: 2026-07-13 13:57:53.399550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052e044604d3'
down_revision: Union[str, None] = 'd778d62ab147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('default_chore_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chores', 'default_chore', ['default_chore_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chores', type_='foreignkey')
    op.drop_column('chores', 'default_chore_id')
    # ### end Alembic commands ###
