"""Update updated_at logic

Revision ID: 13134727c4ed
Revises: b41b7a8c8b39
Create Date: 2025-01-22 21:54:41.100939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13134727c4ed'
down_revision: Union[str, None] = 'b41b7a8c8b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
