"""planned chore is_active field

Revision ID: 286538f8db96
Revises: 8286bc9e6db3
Create Date: 2026-06-15 22:29:31.257360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286538f8db96'
down_revision: Union[str, None] = '8286bc9e6db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_chore', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('planned_chore', 'assigned_to_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('planned_chore_assigned_to_id_fkey', 'planned_chore', type_='foreignkey')
    op.create_foreign_key(None, 'planned_chore', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planned_chore', type_='foreignkey')
    op.create_foreign_key('planned_chore_assigned_to_id_fkey', 'planned_chore', 'users', ['assigned_to_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('planned_chore', 'assigned_to_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('planned_chore', 'is_active')
    # ### end Alembic commands ###
