"""Add fields: icon, icon_bg, icon_color to User and Family

Revision ID: 2b7a20da75a2
Revises: 85707ccb3987
Create Date: 2026-06-23 20:10:08.387549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7a20da75a2'
down_revision: Union[str, None] = '85707ccb3987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('icon_color', sa.String(), server_default='#ffffff', nullable=False))
    op.add_column('family', sa.Column('icon_bg', sa.String(), server_default='linear-gradient(135deg, #e8a87c 0%, #c17a45 100%)', nullable=False))
    op.add_column('users', sa.Column('icon', sa.String(), server_default='material-symbols:person-rounded', nullable=False))
    op.add_column('users', sa.Column('icon_color', sa.String(), server_default='#ffffff', nullable=False))
    op.add_column('users', sa.Column('icon_bg', sa.String(), server_default='linear-gradient(135deg, #8a7f6e 0%, #6b5f50 100%)', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'icon_bg')
    op.drop_column('users', 'icon_color')
    op.drop_column('users', 'icon')
    op.drop_column('family', 'icon_bg')
    op.drop_column('family', 'icon_color')
    # ### end Alembic commands ###
