"""comment

Revision ID: 2d316a9dff0e
Revises: dd11220dcb91
Create Date: 2025-02-19 10:46:52.484192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d316a9dff0e'
down_revision: Union[str, None] = 'dd11220dcb91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chores_logs', 'status',
               existing_type=postgresql.ENUM('awaits', 'canceled', 'approved', name='status_confirm'),
               nullable=False)
    op.alter_column('chores_logs_confirms', 'status',
               existing_type=postgresql.ENUM('awaits', 'canceled', 'approved', name='status_confirm'),
               nullable=False)
    op.alter_column('wallets_transactions', 'transaction_type',
               existing_type=postgresql.ENUM('transfer', 'purchase', 'income', name='transaction_type'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets_transactions', 'transaction_type',
               existing_type=postgresql.ENUM('transfer', 'purchase', 'income', name='transaction_type'),
               nullable=True)
    op.alter_column('chores_logs_confirms', 'status',
               existing_type=postgresql.ENUM('awaits', 'canceled', 'approved', name='status_confirm'),
               nullable=True)
    op.alter_column('chores_logs', 'status',
               existing_type=postgresql.ENUM('awaits', 'canceled', 'approved', name='status_confirm'),
               nullable=True)
    # ### end Alembic commands ###
