"""add exp field to User and Family models

Revision ID: 2fbc150cd55c
Revises: 827f594b9822
Create Date: 2025-12-14 09:53:46.359124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbc150cd55c'
down_revision: Union[str, None] = '827f594b9822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('experience', sa.Integer(), nullable=False, server_default=sa.text("0")))
    op.add_column('users', sa.Column('experience', sa.Integer(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'experience')
    op.drop_column('family', 'experience')
    # ### end Alembic commands ###
