"""add avatar_key field

Revision ID: 3ddd3ae99d05
Revises: bc955af3698c
Create Date: 2025-10-06 22:53:25.535322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddd3ae99d05'
down_revision: Union[str, None] = 'bc955af3698c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('avatar_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_key')
    op.drop_column('family', 'avatar_key')
    # ### end Alembic commands ###
