"""add model QuickPlannedChore

Revision ID: 440c92b5dd56
Revises: 76f76f799cf5
Create Date: 2026-09-06 17:37:02.790127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440c92b5dd56'
down_revision: Union[str, None] = '76f76f799cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_planned_chore',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), server_default='material-symbols:bolt-rounded', nullable=False),
    sa.Column('icon_color', sa.String(), server_default='#ffffff', nullable=False),
    sa.Column('icon_bg', sa.String(), server_default='linear-gradient(135deg, #F59E0B 0%, #F97316 100%)', nullable=False),
    sa.Column('valuation', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('message', sa.String(length=50), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_planned_chore')
    # ### end Alembic commands ###
