"""remove wallet and product models

Revision ID: 611021d58456
Revises: c2d3e4f5a6b7
Create Date: 2026-09-26 17:19:47.751551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '611021d58456'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reward_transactions_planned_chore_id', table_name='reward_transactions')
    op.drop_index('ix_reward_transactions_to_user_created', table_name='reward_transactions')
    op.drop_index('ix_reward_transactions_to_user_id', table_name='reward_transactions')
    op.drop_table('reward_transactions')
    op.drop_table('product_buyers')
    op.drop_table('wallets')
    op.drop_index('ix_peer_transactions_from_user_created', table_name='peer_transactions')
    op.drop_index('ix_peer_transactions_from_user_id', table_name='peer_transactions')
    op.drop_index('ix_peer_transactions_product_id', table_name='peer_transactions')
    op.drop_index('ix_peer_transactions_to_user_created', table_name='peer_transactions')
    op.drop_index('ix_peer_transactions_to_user_id', table_name='peer_transactions')
    op.drop_table('peer_transactions')
    op.drop_index('ix_products_family_id_is_active', table_name='products')
    op.drop_index('ix_products_seller_id_is_active', table_name='products')
    op.drop_table('products')
    op.drop_column('family', 'avatar_extension')
    op.drop_column('family', 'avatar_version')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'avatar_extension')
    op.drop_column('users', 'avatar_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_extension', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.add_column('family', sa.Column('avatar_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('family', sa.Column('avatar_extension', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('products',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('avatar_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avatar_extension', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], name='products_family_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='products_seller_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_products_seller_id_is_active', 'products', ['seller_id', 'is_active'], unique=False)
    op.create_index('ix_products_family_id_is_active', 'products', ['family_id', 'is_active'], unique=False)
    op.create_table('peer_transactions',
    sa.Column('transaction_type', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('from_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('detail', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name='peer_transactions_from_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='peer_transactions_product_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name='peer_transactions_to_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='peer_transactions_pkey')
    )
    op.create_index('ix_peer_transactions_to_user_id', 'peer_transactions', ['to_user_id'], unique=False)
    op.create_index('ix_peer_transactions_to_user_created', 'peer_transactions', ['to_user_id', 'created_at'], unique=False)
    op.create_index('ix_peer_transactions_product_id', 'peer_transactions', ['product_id'], unique=False)
    op.create_index('ix_peer_transactions_from_user_id', 'peer_transactions', ['from_user_id'], unique=False)
    op.create_index('ix_peer_transactions_from_user_created', 'peer_transactions', ['from_user_id', 'created_at'], unique=False)
    op.create_table('wallets',
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallets_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wallets_pkey'),
    sa.UniqueConstraint('user_id', name='wallets_user_id_key')
    )
    op.create_table('product_buyers',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='product_buyers_buyer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_buyers_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_buyers_pkey')
    )
    op.create_table('reward_transactions',
    sa.Column('transaction_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('detail', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('coins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('planned_chore_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planned_chore_id'], ['planned_chore.id'], name='reward_transactions_planned_chore_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name='reward_transactions_to_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='reward_transactions_pkey')
    )
    op.create_index('ix_reward_transactions_to_user_id', 'reward_transactions', ['to_user_id'], unique=False)
    op.create_index('ix_reward_transactions_to_user_created', 'reward_transactions', ['to_user_id', 'created_at'], unique=False)
    op.create_index('ix_reward_transactions_planned_chore_id', 'reward_transactions', ['planned_chore_id'], unique=False)
    # ### end Alembic commands ###
