"""users_permissions

Revision ID: 762c1e796136
Revises: 90e771f6f2cc
Create Date: 2025-02-09 14:24:08.950237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762c1e796136'
down_revision: Union[str, None] = '90e771f6f2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_family_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('should_confirm_chorelog', sa.Boolean(), nullable=False),
    sa.Column('should_confirm_creating_chore', sa.Boolean(), nullable=False),
    sa.Column('can_create_chore', sa.Boolean(), nullable=False),
    sa.Column('can_change_family_name', sa.Boolean(), nullable=False),
    sa.Column('can_kick_user', sa.Boolean(), nullable=False),
    sa.Column('can_invite_users', sa.Boolean(), nullable=False),
    sa.Column('can_promote_user', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_family_permissions')
    # ### end Alembic commands ###
