"""add new models

Revision ID: 8286bc9e6db3
Revises: 910495e14a4a
Create Date: 2026-06-12 22:24:48.629070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8286bc9e6db3'
down_revision: Union[str, None] = '910495e14a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore_schedule',
    sa.Column('chore_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('frequency_type', sa.Enum('daily', 'weekly', 'monthly', name='frequencytypeenum'), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=True),
    sa.Column('last_generated_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_chore',
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('chore_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('awaits', 'canceled', 'approved', name='status_confirm', native_enum=False), nullable=False),
    sa.Column('message', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['chore_schedule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chore_confirmation')
    op.drop_constraint('reward_transactions_chore_completion_id_fkey', 'reward_transactions', type_='foreignkey')
    op.drop_index('ix_reward_transactions_chore_completion_id', table_name='reward_transactions')
    op.drop_column('reward_transactions', 'chore_completion_id')
    op.drop_table('chore_completion')
    op.add_column('reward_transactions', sa.Column('planned_chore_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reward_transactions_planned_chore_id'), 'reward_transactions', ['planned_chore_id'], unique=False)
    op.create_foreign_key(None, 'reward_transactions', 'planned_chore', ['planned_chore_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users_family_permissions', 'should_confirm_chore_completion')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_family_permissions', sa.Column('should_confirm_chore_completion', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('reward_transactions', sa.Column('chore_completion_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reward_transactions', type_='foreignkey')
    op.create_foreign_key('reward_transactions_chore_completion_id_fkey', 'reward_transactions', 'chore_completion', ['chore_completion_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_reward_transactions_planned_chore_id'), table_name='reward_transactions')
    op.create_index('ix_reward_transactions_chore_completion_id', 'reward_transactions', ['chore_completion_id'], unique=False)
    op.drop_column('reward_transactions', 'planned_chore_id')
    op.create_table('chore_confirmation',
    sa.Column('chore_completion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chore_completion_id'], ['chore_completion.id'], name='chore_confirmation_chore_completion_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chore_confirmation_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chore_confirmation_pkey')
    )
    op.create_table('chore_completion',
    sa.Column('chore_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('completed_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chore_id'], ['chores.id'], name='chore_completion_chore_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], name='chore_completion_completed_by_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], name='chore_completion_family_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chore_completion_pkey')
    )
    op.drop_table('planned_chore')
    op.drop_table('chore_schedule')
    # ### end Alembic commands ###
