"""change fk fields

Revision ID: 910495e14a4a
Revises: 2fbc150cd55c
Create Date: 2025-12-17 22:59:46.323092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910495e14a4a'
down_revision: Union[str, None] = '2fbc150cd55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chore_completion', 'chore_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chore_completion', 'completed_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('chore_completion_chore_id_fkey', 'chore_completion', type_='foreignkey')
    op.drop_constraint('chore_completion_completed_by_id_fkey', 'chore_completion', type_='foreignkey')
    op.create_foreign_key(None, 'chore_completion', 'chores', ['chore_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'chore_completion', 'users', ['completed_by_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('products', 'seller_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('products_seller_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_seller_id_fkey', 'products', 'users', ['seller_id'], ['id'], ondelete='SET NULL')
    op.alter_column('products', 'seller_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'chore_completion', type_='foreignkey')
    op.drop_constraint(None, 'chore_completion', type_='foreignkey')
    op.create_foreign_key('chore_completion_completed_by_id_fkey', 'chore_completion', 'users', ['completed_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('chore_completion_chore_id_fkey', 'chore_completion', 'chores', ['chore_id'], ['id'], ondelete='SET NULL')
    op.alter_column('chore_completion', 'completed_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chore_completion', 'chore_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
