"""avatar_version

Revision ID: 9de010232b3e
Revises: 3ddd3ae99d05
Create Date: 2025-10-13 01:44:11.593978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de010232b3e'
down_revision: Union[str, None] = '3ddd3ae99d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('avatar_version', sa.Integer(), nullable=True))
    op.add_column('family', sa.Column('avatar_extension', sa.String(), nullable=True))
    op.drop_column('family', 'avatar_key')
    op.add_column('users', sa.Column('avatar_version', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('avatar_extension', sa.String(), nullable=True))
    op.drop_column('users', 'avatar_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_extension')
    op.drop_column('users', 'avatar_version')
    op.add_column('family', sa.Column('avatar_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('family', 'avatar_extension')
    op.drop_column('family', 'avatar_version')
    # ### end Alembic commands ###
