"""create enums

Revision ID: a49c5e2b2081
Revises: d68eacca7b44
Create Date: 2025-02-19 10:35:41.141080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49c5e2b2081'
down_revision: Union[str, None] = 'd68eacca7b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores_logs', sa.Column('status_new', sa.Enum(name='status_confirm'), nullable=True))
    op.add_column('chores_logs_confirms', sa.Column('status_new', sa.Enum(name='status_confirm'), nullable=True))
    op.add_column('wallets_transactions', sa.Column('transaction_type_new', sa.Enum(name='transaction_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets_transactions', 'transaction_type_new')
    op.drop_column('chores_logs_confirms', 'status_new')
    op.drop_column('chores_logs', 'status_new')
    # ### end Alembic commands ###
