"""Update updated_at field logic

Revision ID: b41b7a8c8b39
Revises: c2b800cc7157
Create Date: 2025-01-22 21:50:42.001167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41b7a8c8b39'
down_revision: Union[str, None] = 'c2b800cc7157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
