"""remove column status PlannedChore

Revision ID: c2b7d659ec1e
Revises: 286538f8db96
Create Date: 2026-06-19 08:13:28.230040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b7d659ec1e'
down_revision: Union[str, None] = '286538f8db96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_chore', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_chore', sa.Column('status', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
