"""PlannedChore.message upgrade linit

Revision ID: c4783f44080d
Revises: 440c92b5dd56
Create Date: 2026-09-10 17:21:38.997760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4783f44080d'
down_revision: Union[str, None] = '440c92b5dd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planned_chore', 'message',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planned_chore', 'message',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
