"""add coins field to transation log

Revision ID: d68eacca7b44
Revises: 762c1e796136
Create Date: 2025-02-12 18:09:38.544122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68eacca7b44'
down_revision: Union[str, None] = '762c1e796136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets_transactions', sa.Column('coins', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets_transactions', 'coins')
    # ### end Alembic commands ###
