"""Add fields icon, icon_color, icon_bg to Chore and DefaultChore

Revision ID: d778d62ab147
Revises: 2b7a20da75a2
Create Date: 2026-06-29 20:45:52.025651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd778d62ab147'
down_revision: Union[str, None] = '2b7a20da75a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('icon_color', sa.String(), server_default='#ffffff', nullable=False))
    op.add_column('chores', sa.Column('icon_bg', sa.String(), server_default='linear-gradient(135deg, #8a7f6e 0%, #6b5f50 100%)', nullable=False))
    op.add_column('default_chore', sa.Column('icon_color', sa.String(), server_default='#ffffff', nullable=False))
    op.add_column('default_chore', sa.Column('icon_bg', sa.String(), server_default='linear-gradient(135deg, #8a7f6e 0%, #6b5f50 100%)', nullable=False))
    op.drop_column('default_chore', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('default_chore', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('default_chore', 'icon_bg')
    op.drop_column('default_chore', 'icon_color')
    op.drop_column('chores', 'icon_bg')
    op.drop_column('chores', 'icon_color')
    # ### end Alembic commands ###
