"""comment

Revision ID: dd11220dcb91
Revises: e1485f95d188
Create Date: 2025-02-19 10:44:12.180806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd11220dcb91'
down_revision: Union[str, None] = 'e1485f95d188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores_logs', sa.Column('status', sa.Enum(name='status_confirm'), nullable=True))
    op.drop_column('chores_logs', 'status_new')
    op.add_column('chores_logs_confirms', sa.Column('status', sa.Enum(name='status_confirm'), nullable=True))
    op.drop_column('chores_logs_confirms', 'status_new')
    op.add_column('wallets_transactions', sa.Column('transaction_type', sa.Enum(name='transaction_type'), nullable=True))
    op.drop_column('wallets_transactions', 'transaction_type_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets_transactions', sa.Column('transaction_type_new', postgresql.ENUM('transfer', 'purchase', 'income', name='transaction_type'), autoincrement=False, nullable=True))
    op.drop_column('wallets_transactions', 'transaction_type')
    op.add_column('chores_logs_confirms', sa.Column('status_new', postgresql.ENUM('awaits', 'canceled', 'approved', name='status_confirm'), autoincrement=False, nullable=True))
    op.drop_column('chores_logs_confirms', 'status')
    op.add_column('chores_logs', sa.Column('status_new', postgresql.ENUM('awaits', 'canceled', 'approved', name='status_confirm'), autoincrement=False, nullable=True))
    op.drop_column('chores_logs', 'status')
    # ### end Alembic commands ###
