"""comment

Revision ID: e1485f95d188
Revises: a49c5e2b2081
Create Date: 2025-02-19 10:43:39.932546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1485f95d188'
down_revision: Union[str, None] = 'a49c5e2b2081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chores_logs', 'status')
    op.drop_column('chores_logs_confirms', 'status')
    op.drop_column('wallets_transactions', 'transaction_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets_transactions', sa.Column('transaction_type', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('chores_logs_confirms', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('chores_logs', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
