"""add avatar fields to product

Revision ID: e4a428f09547
Revises: 9de010232b3e
Create Date: 2025-10-31 03:59:51.661110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a428f09547'
down_revision: Union[str, None] = '9de010232b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('avatar_version', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('avatar_extension', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'avatar_extension')
    op.drop_column('products', 'avatar_version')
    # ### end Alembic commands ###
